# Generated by Django 3.2.7 on 2022-02-12 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('field', models.CharField(blank=True, max_length=50, null=True)),
                ('search_frequency', models.CharField(choices=[('', ''), ('frequently', 'Several times a day'), ('usually', 'Once per day'), ('sometimes', 'Several times a week'), ('rarely', 'Less than once a week')], max_length=50)),
                ('search_history', models.CharField(choices=[('', ''), ('very long', 'five years or longer'), ('long', 'three to five years'), ('short', 'one to three years'), ('very short', 'less than one year')], max_length=50)),
                ('signup_time', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
                ('login_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswordRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(default='a02a46f8351f', max_length=50)),
                ('expire', models.IntegerField(default=1644817071)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_system.user')),
            ],
        ),
    ]
