# Generated by Django 3.2.7 on 2021-12-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordrequest',
            name='expire',
            field=models.IntegerField(default=1639828278),
        ),
        migrations.AlterField(
            model_name='resetpasswordrequest',
            name='token',
            field=models.CharField(default='f8db8ad2be97', max_length=50),
        ),
    ]
