# Generated by Django 4.1 on 2023-07-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_auto_20220212_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordrequest',
            name='expire',
            field=models.IntegerField(default=1688846747),
        ),
        migrations.AlterField(
            model_name='resetpasswordrequest',
            name='token',
            field=models.CharField(default='e8e1d8153ecd', max_length=50),
        ),
    ]
