# Generated by Django 4.1 on 2023-07-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_auto_20211216_2351'),
        ('user_system', '0003_alter_resetpasswordrequest_expire_and_more'),
    ]

    operations = [
    ]
