# Generated by Django 4.1 on 2023-07-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0004_merge_20230709_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordrequest',
            name='expire',
            field=models.IntegerField(default=1689039079),
        ),
        migrations.AlterField(
            model_name='resetpasswordrequest',
            name='token',
            field=models.CharField(default='4294edbb2f48', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='search_frequency',
            field=models.CharField(blank=True, choices=[('', ''), ('frequently', 'Several times a day'), ('usually', 'Once per day'), ('sometimes', 'Several times a week'), ('rarely', 'Less than once a week')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='search_history',
            field=models.CharField(blank=True, choices=[('', ''), ('very long', 'five years or longer'), ('long', 'three to five years'), ('short', 'one to three years'), ('very short', 'less than one year')], max_length=50, null=True),
        ),
    ]
