# Generated by Django 4.1 on 2023-07-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0005_alter_resetpasswordrequest_expire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordrequest',
            name='expire',
            field=models.IntegerField(default=1689108621),
        ),
        migrations.AlterField(
            model_name='resetpasswordrequest',
            name='token',
            field=models.CharField(default='df31a10fea9f', max_length=50),
        ),
    ]
